name: tempalteflutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.3+3

environment:
  sdk: ">=2.14.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  modal_progress_hud_nsn: ^0.3.0
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  shared_preferences: ^2.0.13
  font_awesome_flutter: ^10.1.0
  country_code_picker: ^2.0.2
  image_cropper: ^3.0.0
  cached_network_image: ^3.2.0
  url_launcher: ^6.1.0
  intl: ^0.17.0
  page_indicator: ^0.4.1
  fluttertoast: ^8.0.9
  bottom_navy_bar: ^6.0.0
  persistent_bottom_nav_bar: ^5.0.2
  sticky_headers: ^0.3.0+2
  percent_indicator: ^4.0.0
  razorpay_flutter: ^1.3.0
  flutter_circle_color_picker: ^0.3.0
  aamarpay: ^1.0.3
  flutter_countdown_timer: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/appUpdate.png
    - assets/updateButtonImage.png
    - assets/cricketImage1.png
    - assets/cricketImage2.png
    - assets/cricketImage3.png
    - assets/cricketGround.png
    - assets/ruppeIcon.png
    - assets/cup.png
    - assets/playerImage.png
    - assets/userAvatar.png
    - assets/pts.png
    - assets/greencup.png
    - assets/users.png
    - assets/arrowE.png
    - assets/arrowG.png
    - assets/arrowL.png
    - assets/notificationRupee.png
    - assets/notificationCup.png
    - assets/SouthAfrica.png
    - assets/India.png
    - assets/Bangladesh.png
    - assets/Zimbabwe.png
    - assets/Sirilanka.png
    - assets/Netherlands.png
    - assets/Pakistan.png
    - assets/WestIndies.png
    - assets/tv.png
    - assets/cname/123.png
    - assets/cname/119.png
    - assets/g1.png
    - assets/wallet.png
    - assets/lineups.png
    - assets/prize.png
    - assets/guaranteed.png
    - assets/cname/
    - assets/baseballPlayer.jpg
    - assets/cricketPlayer.jpg
    - assets/footballPlayer.jpg
    - assets/playerProfilePic.jpg
    - assets/kabadiplayer.jpg
    - assets/stump.png
    - assets/trophy.png
    - assets/badge.png
    - assets/arrow_down.png

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-RegularItalic.ttf
        - asset: fonts/Poppins-Light.ttf
        - asset: fonts/Poppins-LightItalic.ttf
        - asset: fonts/Poppins-Thin.ttf
        - asset: fonts/Poppins-ThinItalic.ttf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
